### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by PillarChen** [lambiengcode/flutter-chatgpt-completions#8]
E/flutter ( 6185): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: status code: 400, error: [] is too short - 'messages'
E/flutter ( 6185): #0      TextCompletionsRepository._handleListenBodyBytesTurbo (package:chatgpt_completions/src/repository/text_completions_repository.dart:201:9)
E/flutter ( 6185): #1      TextCompletionsRepository.textCompletions.<anonymous closure>.<anonymous closure> (package:chatgpt_completions/src/repository/text_completions_repository.dart:77:15)
E/flutter ( 6185): #2      DecoderQueueService.runQueue (package:chatgpt_completions/src/services/decoder_queue.dart:21:19)
E/flutter ( 6185): #3      DecoderQueueService.addQueue (package:chatgpt_completions/src/services/decoder_queue.dart:14:5)
E/flutter ( 6185): #4      TextCompletionsRepository.textCompletions.<anonymous closure> (package:chatgpt_completions/src/repository/text_completions_repository.dart:75:40)
E/flutter ( 6185): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter ( 6185): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 6185): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 6185): #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 6185): #9      _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter ( 6185): #10     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter ( 6185): #11     _DoStreamSink.onData (package:rxdart/src/transformers/do.dart:40:10)
E/flutter ( 6185): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter ( 6185): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 6185): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 6185): #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 6185): #16     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter ( 6185): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter ( 6185): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 6185): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 6185): #20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 6185): #21     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter ( 6185): #22     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter ( 6185): #23     TimerStream._buildController.<anonymous closure>.<anonymous closure> (package:rxdart/src/streams/timer.dart:51:22)
E/flutter ( 6185): #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 6185): #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 6185): #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 6185): #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

**Comment by chopper985** [comment]
Can you provide code that can reproduce the issue?
